from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('community/', views.community, name='community'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('create/', views.create_folder, name='create_folder'),
    path('folder/<uuid:folder_id>/', views.folder_detail, name='folder_detail'),
    path('folder/<uuid:folder_id>/upload/', views.upload_files, name='upload_files'),
    path('folder/<uuid:folder_id>/delete/', views.delete_folder, name='delete_folder'),
    path('folder/<uuid:folder_id>/edit/', views.edit_folder, name='edit_folder'),
    path('file/<int:file_id>/', views.file_detail, name='file_detail'),
    path('file/<int:file_id>/download/', views.download_file, name='download_file'),
    path('file/<int:file_id>/delete/', views.delete_file, name='delete_file'),
    path('settings/', views.user_settings, name='user_settings'),
    path('settings/change-password/', views.change_password, name='change_password'),
    path('settings/update-profile/', views.update_profile, name='update_profile'),
    path('settings/add-link/', views.add_link, name='add_link'),
    path('settings/delete-link/<int:link_id>/', views.delete_link, name='delete_link'),
    path('subscription/', views.subscription_plans, name='subscription_plans'),
    path('subscription/upgrade/<str:plan>/', views.upgrade_subscription, name='upgrade_subscription'),
    path('subscription/order/<str:plan>/', views.create_payment_order, name='create_payment_order'),
    path('subscription/verify/', views.verify_payment, name='verify_payment'),
    path('subscription/success/<str:plan>/', views.payment_success, name='payment_success'),
    path('subscription/downgrade/', views.downgrade_to_free, name='downgrade_to_free'),
    path('subscription/custom-domain/', views.update_custom_domain, name='update_custom_domain'),
    # Public share — directly serves website or file list
    path('share/<uuid:folder_id>/', views.share_page, name='share_page'),
    path('share/<uuid:folder_id>/info/', views.share_info, name='share_info'),
    path('folder/<uuid:folder_id>/preview/', views.preview_website, name='preview_website'),
    path('file/<int:file_id>/preview/', views.preview_file_as_website, name='preview_file_as_website'),
    path('file/<int:file_id>/serve/', views.serve_website_file, name='serve_website_file'),
    # Admin Dashboard
    path('admin-panel/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-panel/database/', views.admin_database, name='admin_database'),
    path('admin-panel/login/', views.admin_login_view, name='admin_login'),
    path('admin-panel/users/', views.admin_users, name='admin_users'),
    path('admin-panel/users/<int:user_id>/', views.admin_user_detail, name='admin_user_detail'),
    path('admin-panel/users/<int:user_id>/delete/', views.admin_delete_user, name='admin_delete_user'),
    path('admin-panel/users/<int:user_id>/toggle-status/', views.admin_toggle_user_status, name='admin_toggle_user_status'),
    path('admin-panel/folders/', views.admin_folders, name='admin_folders'),
    path('admin-panel/folders/<uuid:folder_id>/delete/', views.admin_delete_folder, name='admin_delete_folder'),
    path('admin-panel/folders/<uuid:folder_id>/toggle-visibility/', views.admin_toggle_folder_visibility, name='admin_toggle_folder_visibility'),
]
